(define (domain pick-place)
 (:requirements :strips)
  (:predicates
    (Arm ?a)
    (Item ?o)
    (Surf ?s)
    (Pose ?o ?p)
    (BPose ?o ?bp ?s)
    (Grasp ?o ?g)
    (Traj ?t)
    (PickMotion ?q1 ?t)
    (PlaceMotion ?q1 ?t ?q2)
    (Supported ?o ?p ?s)
    (Vis ?o ?bp ?q)
    (AtPose ?o ?p)
    (AtGrasp ?a ?o ?g)
    (HandEmpty ?a)
    (Conf ?q)
    (AtConf ?q)
    (On ?o ?s)
    (Holding ?a ?o)
  )
  (:action pick
    :parameters (?a ?o ?p ?g ?q1 ?t)
    :precondition (and (Arm ?a)
                       (HandEmpty ?a)
                       (Item ?o)
                       (AtPose ?o ?p)
                       (PickMotion ?q1 ?t)
                       (AtConf ?q1))
    :effect (and (not (AtConf ?q1))
                 (AtGrasp ?a ?o ?g)
                 (not (AtPose ?o ?p))
                 (not (HandEmpty ?a)))
  )
  (:derived (On ?o ?s)
    (exists (?p) (and (Supported ?o ?p ?s)
                      (AtPose ?o ?p)))
  )
  (:derived (Holding ?a ?o)
    (exists (?g) (and (Arm ?a) (Grasp ?o ?g)
                      (AtGrasp ?a ?o ?g)))
  )
)