(define (domain pick-place)
;; TODO: Add receptacle in domain
 (:requirements :strips)
 (:predicates
   (Arm ?a)
   (Object ?o)
   (Grasp ?o ?g)
   (AtPose ?o ?p)
   (Pose ?o ?p) 
   (Graspable ?o)
   (HandEmpty)
   (Holding ?o)
   (BConf ?q)
   (AtBConf ?q)
   (Clear ?o)
 )

 (:action pick
   :parameters (?a ?o ?p ?g ?bq)
   :precondition (and (Arm ?a)
                     (Object ?o)
                     (Pose ?o ?p)
                     (Grasp ?o ?g) 
                     (AtPose ?o ?p)
                     (Graspable ?o)
                     (HandEmpty)
                     (BConf ?bq)
                     (AtBConf ?bq)
                     (Clear ?o))
   :effect (and (Holding ?o)
               (not (AtPose ?o ?p))
               (not (HandEmpty)))
 )

 (:action place
   :parameters (?a ?o ?p ?bq) 
   :precondition (and (Arm ?a)
                     (Object ?o)
                     (Pose ?o ?p)
                     (Holding ?o)
                     (BConf ?bq)
                     (AtBConf ?bq))
   :effect (and (AtPose ?o ?p)
               (HandEmpty)
               (Clear ?o))
 )
)
