(define (domain pick-place)
 (:requirements :strips)
 (:predicates
   (Arm ?a)
   (Object ?o)
   (Grasp ?o ?g)
   (AtPose ?o ?p)
   (Pose ?o ?p) 
   (Graspable ?o)
   (HandEmpty)
   (Holding ?o)
   (BConf ?q)
   ; (AtBConf ?q)
   (Clear ?o)
   (Loc ?l)
   (Supported ?o ?p ?l)
 )

 (:action pick
   :parameters (?a ?o ?p ?g ?bq ?l)
   :precondition (and (Arm ?a)
                     (Object ?o)
                     (Pose ?o ?p)
                     (Grasp ?o ?g) 
                     (AtPose ?o ?p)
                     (Graspable ?o)
                     (HandEmpty)
                     (BConf ?bq)
                     ; (AtBConf ?bq)
                     (Loc ?l)
                     (Supported ?o ?p ?l)
                     (Clear ?o))
   :effect (and (Holding ?o)
               (not (AtPose ?o ?p))
               (not (HandEmpty)))
 )

  (:action place
   :parameters (?a ?o ?p ?bq ?l)
   :precondition (and (Arm ?a)
                     (Object ?o)
                     (Holding ?o)
                     (BConf ?bq)
                     ; (AtBConf ?bq)
                     (Loc ?l)
                     (not (AtPose ?o ?p)))
   :effect (and (AtPose ?o ?p)
               (HandEmpty)
               (Clear ?o)
               (not (Holding ?o)))
  )
)
