(define (stream pick-place)
  (:stream sample-grasp
    :inputs (?o)
    :domain (Item ?o)
    :outputs (?g)
    :certified (Grasp ?o ?g)
  )
  (:stream plan-pick
    :inputs (?a ?o ?p ?g ?q1)
    :domain (and (Item ?o)
                 (Arm ?a)
                 (Pose ?o ?p)
                 (Grasp ?o ?g)
                 (Conf ?q1))
    :outputs (?t)
    :certified (and (PickMotion ?q1 ?t)
                    (Traj ?t))
  )
)